title: Car Park
description: Application for Car Park management
theme: just-the-docs

url: https://fpmi-tp2024.github.io/tpmp-gpd-lab5-hryakopluxi/

nav:
  - title: About
    url: /
  - title: Diagrams
    url: /
  - title: Assignment
    url: /
 - title: Contributors
    url: /


aux_links:
  GitHub Repository: https://github.com/fpmi-tp2024/tpmp-gpd-lab5-hryakopluxi
