name: main
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
     
      - name: Build
        run: make build
        continue-on-error: false
     
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
     
      - name: Install dependencies
        run: sudo apt-get install libgtest-dev
        continue-on-error: false
     
      - name: Run tests
        run: make test
        continue-on-error: false